project_id = "uzrdcmkxqertljcxdezd"

[functions.translate-text]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.recognize-tracking]
verify_jwt = false
